name: Multiple Architecture Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release-*'
    tags:
      - 'v*'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-build:
    uses: konveyor/release-tools/.github/workflows/build-push-images.yaml@main
    with:
      registry: "quay.io/konveyor"
      image_name: "tackle2-addon-analyzer"
      containerfile: "./Dockerfile"
      architectures: '[ "amd64", "arm64" ]'
      pre_build_cmd: |
        TAG=${GITHUB_REF_NAME/main/latest}
        sed -i "s,FROM quay.io/konveyor/windup-shim\:latest,FROM quay.io/konveyor/windup-shim:${TAG}," Dockerfile
        sed -i "s,FROM quay.io/konveyor/analyzer-lsp\:latest,FROM quay.io/konveyor/analyzer-lsp:${TAG}," Dockerfile
    secrets:
      registry_username: ${{ secrets.QUAY_PUBLISH_ROBOT }}
      registry_password: ${{ secrets.QUAY_PUBLISH_TOKEN }}
